version: "3.8"
services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: frontend-dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_FRONT_URL=http://localhost:3000/
      - REACT_APP_BACK_URL=http://localhost:4000/
  db-dev:
    image: mysql:latest
    container_name: db-dev
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    expose:
      - '3306'
    volumes:
      - db-dev-volume:/var/lib/mysql
  backend-dev:
    depends_on:
      - db-dev
    build: ./backend
    container_name: backend-dev
    environment:
      - DB_HOST=db-dev
      - DB_PORT=3306
      - FRONT_URL=http://localhost:3000/
      - BACK_URL=http://localhost:4000/
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - /app/node_modules/

volumes:
  db-dev-volume:

