version: "3.8"
services:
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    container_name: frontend-prod
    expose:
      - '3000'
    environment:
      - REACT_APP_FRONT_URL=${FRONT_URL}
      - REACT_APP_BACK_URL=${BACK_URL}
  db-prod:
    image: mysql:latest
    container_name: db-prod
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    expose:
      - '3306'
    volumes:
      - db-prod-volume:/var/lib/mysql
  backend-prod:
    depends_on:
      - db-prod
    build: ./backend
    container_name: backend-prod
    environment:
      - DB_HOST=db-prod
      - DB_PORT=3306
      - FRONT_URL=${FRONT_URL}
      - BACK_URL=${BACK_URL}
    expose:
      - '4000'
    stdin_open: true
    tty: true
  nginx-prod:
    build: ./nginx
    container_name: nginx-prod
    restart: always
    ports:
      - '80:80'
    depends_on:
      - backend-prod
      - db-prod
      - frontend-prod

volumes:
  db-prod-volume:

